version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      ETHEREAL_EMAIL: chelsie.boehm6@ethereal.email
      ETHEREAL_PASSWORD: GaZbAHrhFF7JB6paH2
      DB_URL: postgres://postgres:postgres@db:5432/Genesis
    volumes:
      - ./data:/data
      - ./migration:/app/migration
    networks:
      - genesis

  db:
    image: postgres:latest
    container_name: genesis_db_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Genesis
      DATABASE_HOST: db
    ports:
      - '5432:5432'
    volumes:
      - ./data:/data
    networks:
      - genesis
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  genesis:
    driver: bridge
